### ISSUE TITLE
Prometheus: error "Unable to look up a name ... an attribute in template string ({{ prometheus_tdp_targets | dict2items }})"

### ISSUE THREAD

**Issue by kpgtek** [TOSIT-IO/tdp-observability#42]
I got the following error while running ```prometheus_server_config``` operation:
```
TASK [tosit.tdp_observability.server : Template Prometheus file_sd targets for TDP components] *************************************************
fatal: [master-01]: FAILED! => {}

MSG:

Unable to look up a name or access an attribute in template string ({{ prometheus_tdp_targets | dict2items }}).
Make sure your variable name does not contain invalid characters like '-': dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead.
```

**Comment by kpgtek** [comment]
Why the following target has been removed from ```prometheus_tdp_targets``` variable?
```
  exporter_node:
    component: exporter_node
    group: exporter_node
    port: "{{ exporter_node_http_port }}"
    service: node
```
